### ISSUE TITLE
Plant climbing

### ISSUE THREAD

**Issue by Vutshi** [TakuikaNinja/smb1-bugfix#2]
Mario can't climb the plant, and when he tries to go right, he gets teleported back.

https://github.com/user-attachments/assets/90d1cd2e-2608-472a-86e9-805d8910c943

The game build is approximately 20537e3ff2d66935f826d32ae14f5c2eeb7227d2

**Comment by TakuikaNinja** [comment]
This is a known problem with how the fix for the vine screen wrap bug is implemented. Will look into it at some point.

**Comment by TakuikaNinja** [comment]
Should be fixed by 95c7bed. The vine's collision is unloaded once the sprites are offscreen, eliminating any chance of the wraparound bug occurring. I've also partially reimplemented the original facing direction logic when grabbing vines, where the player is forced to stay on the right-hand side if they are close to the left edge of the screen.
